---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: 
  - "Claudia Frick"
  - "Philipp Zeuner"
  - "Caleb Buchert"
  - "Daniela Markus"
  - "Norma Fötsch"
  - "Yvonne Fischer"
  - "Emma Wieseler"
  - "Sabrina Ramünke"
  - "Nik Baumann"
title: "Queer sein ist (bibliotheks)politisch"
abstract: "Seit November 2023 gibt es die Queerbrarians, ein deutschsprachiges Netzwerk queerer Bibliotheksmenschen. Anhand der beim ersten Treffen zusammengetragenen Themen legt dieser Beitrag neben den Beweggründen für die Entstehung des Netzwerks auch dessen Ideen und Vorstellungen einer queerfreundlicheren Bibliothekswelt dar. Queerness ist in Bibliotheken im deutschsprachigen Raum ein noch immer unterrepräsentiertes Thema, egal ob vor oder hinter der Theke, im Bestand oder in den Katalogen. Das muss sich ändern. Die Queerbrarians und dieser Beitrag möchten diese Veränderung anstoßen, erläutern, warum sie wichtig und wertvoll ist und für eine queere Perspektive sensibilisieren. Dass dabei (bibliotheks)politische Überlegungen ins Spiel kommen, ist beinahe unvermeidlich, denn queer sein ist (bibliotheks)politisch."
pdf: "https://doi.org/10.18452/29144"
doi: "10.18452/29144"
date: 2024-07-12
comments: false
sharing: true
footer: true

---