---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: 
    - "Dina Heß"
    - "Susanne Hein"
    - "Karsten Schuldt"
title: "Interview mit der Redaktion von <q>Forum Musikbibliothek</q>"
pdf: "main.pdf"
date: 2024-07-08
comments: false
sharing: true
footer: true

---