---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: 
  - "Claudia Frick"
  - "Philipp Zeuner"
  - "Caleb Buchert"
  - "Daniela Markus"
  - "Norma Fötsch"
  - "Yvonne Fischer"
  - "Emma Wieseler"
  - "Sabrina Ramünke"
  - "Nik Baumann"
title: "Being queer (in libraries) is political"
abstract: "Queerbrarians is a German-speaking network of queer librarians and people working or aiming to work in libraries or library institutions that was founded in November 2023. Based upon topics gathered at the first network meeting, this article presents the motivations for the creation of the network as well as its ideas and visions of more queer-friendly libraries. Queerness is still an underrepresented topic in libraries in German-speaking countries, whether it’s about patrons, about people working in libraries, or about the collections or the catalogs. This needs to change. Queerbrarians and this article want to initiate this change, explain why it is important and valuable, and raise awareness for the queer perspective. It is almost inevitable that (library) policy considerations will come into play, because being queer (in libraries) is political."
pdf: "https://doi.org/10.18452/29148"
doi: "10.18452/29148"
date: 2024-07-12
comments: false
sharing: true
footer: true

---