---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: 
- Redaktion LIBREAS
title: "Editorial #45: The Sound of Libraries"
pdf: "https://doi.org/10.18452/29132"
doi: "10.18452/29132"
date: 2024-07-12
comments: false
sharing: true
footer: true

---