---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: 
  - "Michel Roth"
  - "Felicitas Erb"
  - "Anna Alexay"
  - "Oleksandra Katsalap"
  - "Oliver Rutz"
title: "Die Bibliothek von Basel. Unendliche Klänge und eine neue Heimat"
pdf: "https://doi.org/10.18452/29137"
doi: "10.18452/29137"
date: 2024-07-01
comments: false
sharing: true
footer: true

---
