---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: "Julia Kohlbach"
title: "Von wegen ein stilles Örtchen"
pdf: "main.pdf"
date: 2024-07-08
comments: false
sharing: true
footer: true

---