---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: 
  - "Alexander Struck"
title: "Library Music – Audio for the Screens from Libraries of Sound"
abstract: "The article introduces the concept of library music. We document different terms and use cases as well as the diversity of genres, pseudonyms and composers. Metadata is of special importance to make this utilitarian music findable and increase its reuse. The section on economics discusses marketing strategies, rights management and experiments."
abstractalt: "Der Artikel führt das Konzept Library Music ein. Wir dokumentieren verschiedene Nutzungsbedingungen, Nutzungsszenarien und die Verschiedenartigkeit der abgebildeten Genres, der Pseudonyme und Diversität der Komponist*innen. Der Abschnitt zu Metadaten arbeitet deren Relevanz für die Auffindbarkeit und Nachnutzung vorproduzierter Musik heraus. Die wirtschaftlichen Aspekte werden anhand von Marketingstrategien, Rechtemanagement und Experimenten besprochen."
pdf: "https://doi.org/10.18452/29141"
doi: "10.18452/29141"
date: 2024-07-01
comments: false
sharing: true
footer: true

---
