---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: 
  - "Sarah Themel"
title: "The Sound of Libraries – ein Hörbild der Stadt Wien Büchereien"
pdf: "https://doi.org/10.18452/29135"
doi: "10.18452/29135"
date: 2024-07-01
comments: false
sharing: true
footer: true

---
