---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #14 (Frühling–Sommer 2024)"
pdf: "https://doi.org/10.18452/..."
doi: "10.18452/..."
date: 2024-07-08
comments: false
sharing: true
footer: true

---