---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: 
  - "Insa Hansen-Goos"
  - "Barbara Heindl"
  - "Harald Krewer" 
  - "Christian Mathieu"
title: "Hinter den Geräuschkulissen &mdash; ein Projekt zur akustischen Vermessung 
des Scharoun-Gebäudes der Staatsbibliothek zu Berlin"
abstract: "Die von Hans Scharoun entworfene Staatsbibliothek am Kulturforum ist ein zentraler Ort wissenschaftlicher wie literarischer Textproduktion in Berlin. Neben der hohen Raumqualität dieser Ikone moderner Bibliotheksarchitektur befördert auch ihre charakteristische, von Wim Wenders sogar in seinem Film <i>Der Himmel über Berlin</i> (1987) ästhetisierte Geräuschkulisse ganz wesentlich die kreative Schreibarbeit im Lesesaal.</br>In diesem Beitrag geht es um ein in Kooperation mit dem Hörverlag speak low sowie der Medienwissenschaftlerin Hannah Wiemer realisiertes Projekt der Staatsbibliothek zur akustischen Vermessung ihres Scharoun-Gebäudes am Kulturforum. Am Vorabend von dessen Generalinstandsetzung soll damit sowohl dem Inspirationspotential der Sounds of Stabi nachgegangen als auch und vor allem die Möglichkeit geschaffen werden, sich die Staatsbibliothek nach Hause zu holen &mdash; gerade während ihrer baubedingten Schließzeit."
abstractalt: "The Staatsbibliothek at the Kulturforum, designed by Hans Scharoun, is a central space for scientific and literary text production in Berlin. In addition to the high spatial quality of this icon of modern library architecture, its characteristic soundscape, which was even aestheticized by Wim Wenders in his film <i>Wings of Desire</i> (1987), also significantly promotes creative writing in the reading room.</br>This article discusses a project realized by the Staatsbibliothek in collaboration with the publishing house speak low and media scientist Hannah Wiemer to conduct an acoustic survey of the Scharoun building at the Kulturforum. On the eve of its upcoming renovation, the aim is both to explore the inspirational potential of the Sounds of Stabi and, above all, to create the opportunity to take the Staatsbibliothek home &mdash; especially during its construction-related closure."
pdf: "https://doi.org/10.18452/29136"
doi: "10.18452/29136"
date: 2024-07-01
comments: false
sharing: true
footer: true

---
