---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "45"
year: "2024"
contributor: "Boris Queckbörner"
title: "Vom <q>Sound-of-Silence</q> – Anmerkungen zur Soundscape Bibliothek"
abstract: "Der Beitrag stellt in aller Kürze das Konzept der Soundscape vor, wie es vor allem von R. Murray Schafer (1977) entwickelt worden ist. Ausgehend von Schafer wird in der Folge argumentiert, dass es sich bei der Bibliothek um eine spezifische Ausprägung einer Soundscape handelt, die im Kontrast zur gesellschaftlichen Umwelt als klangliche Heterotopie (Hi-Fi-Soundscape) beschrieben werden kann. Diese Hi-Fi-Umgebung trägt maßgeblich zur Entstehung einer lernförderlichen Atmosphäre in Bibliotheken bei, die unter anderem mit Begriffen wie <q>Bibliothekskonzentration</q> oder die <q>Out-of-the-Box-Konzentration</q> (Fansa, 2008) beschrieben worden ist und als Alleinstellungsmerkmal der Einrichtung gilt. Das Soundscape-Konzept ermöglicht hier eine neue analytische Perspektive auf diese Zusammenhänge, wodurch ein Mehrwert unter anderem für die bibliothekarischen Diskussionen um den physischen Lernort Bibliothek generiert werden kann. Zum Abschluss werden einige potentielle Anschlussthemen skizziert."
abstractalt: "This article briefly introduces the concept of the soundscape as primarily conceptualized by R. Murray Schafer (1977). Based on Schafer, it is argued that the library is a specific form of soundscape that can be described as a sonic heterotopia (Hi-Fi-Soundscape) in contrast to the social environment. This hi-fi environment contributes significantly to an atmosphere conducive to learning, which has been described with terms such as <q>library concentration</q> (Bibliothekskonzentration) or <q>out-of-the-box concentration</q> (Fansa, 2008) and is considered a unique selling point of libraries. The soundscape concept enables a new analytical perspective on these contexts, which can add value to discussions about the physical learning location of the library as a whole. Finally, some potential follow-up topics are outlined."
pdf: "main.pdf"
date: 2024-07-01
comments: false
sharing: true
footer: true

---
